// Generated by CoffeeScript 1.9.2
var $defaultTracker, $defaults, $pixel, $sessionid, $siteid, $trakless2, Emitter, attrs, cookie, defaults, doc, domevent, domify, fn, getImage, i, j, k, len, len1, mytrakless, myutil, prefix, query, ref, ref1, script, tracker, trakless, traklessParent, util, uuid, webanalyser, win, xstore;

xstore = require('xstore');

Emitter = require('emitter');

domevent = require('domevent');

cookie = require('cookie');

defaults = require('defaults');

query = require('querystring');

uuid = require('uuid');

webanalyser = require('webanalyser');

domify = require('domify');

win = window;

doc = win.document;

$defaultTracker = null;

$siteid = 0;

$pixel = '/pixel.gif';

$defaults = null;

$sessionid = cookie('trakless:usid');

if ($sessionid == null) {
  $sessionid = new Date().getTime();
  cookie('tls:usid', $sessionid, {
    path: '/'
  });
}


/**
 * Send image request to server using GET.
 * The infamous web bug (or beacon) is a transparent, single pixel (1x1) image
#
 */

getImage = function(cfgUrl, request, callback) {
  var image;
  image = new Image(1, 1);
  image.onload = function() {
    var iterator;
    iterator = 0;
    if (typeof callback === 'function') {
      callback();
    }
  };
  image.src = cfgUrl + (cfgUrl.indexOf('?') < 0 ? '?' : '&') + request;
  return image;
};


/**
 *  util
 */

util = (function() {
  function util() {}


  /**
   * allow for getting all attributes
  #
   * @param {HTMLElement} el - element
   * @return {Object}
   */

  util.prototype.allData = function(el) {
    var attr, camelCaseName, data, i, k, len, name, ref;
    data = {};
    if ((el != null)) {
      ref = el.attributes;
      for (k = i = 0, len = ref.length; i < len; k = ++i) {
        attr = ref[k];
        name = attr.name.replace(/^data-/g, '');
        camelCaseName = name.replace(/-(.)/g, function($0, $1) {
          return $1.toUpperCase();
        });
        data[camelCaseName] = attr.value;
      }
    }
    return data;
  };


  /**
   * mini jquery
  #
   */

  util.prototype.$ = domevent;


  /**
   * parse a string to JSON, return string if fail
  #
   * @param {String} v - string value
   * @return {Object}
   */

  util.prototype.stringToJSON = function(v) {
    var v2;
    if (typeof v === "string") {
      if (v.indexOf('{') >= 0 || v.indexOf('[') >= 0) {
        v2 = domevent.parseJSON(v);
        if (!(v2 == null)) {
          return v2;
        }
      }
    }
    return v;
  };


  /**
   * get or set session data - store in cookie
   * if no value is provided, then it is a get
  #
   * @param {String} k - key
   * @param {Object} v - value
   * @return {Object}
   */

  util.prototype.session = function(k, v) {
    if ((v != null)) {
      if (!(typeof v === "string")) {
        v = domevent.toJSON(v);
      }
      cookie('tls:' + k, v, {
        path: '/'
      });
      return v;
    }
    v = cookie('tls:' + k);
    if (typeof v === 'undefined') {
      return v;
    }
    return this.stringToJSON(v);
  };


  /**
   * document ready
  #
   */

  util.prototype.ready = domevent.ready;


  /**
   * trim
  #
   */

  util.prototype.trim = function(v) {
    return v.replace(/^\s+|\s+$/gm, '');
  };


  /**
   * set a class
  #
   */

  util.prototype.setClass = function(el, cls) {
    return domevent(el).set('$', cls);
  };


  /**
   * append or retrieve html
  #
   */

  util.prototype.html = function(el, html) {
    var newDiv;
    if (html != null) {
      while (el.firstChild != null) {
        el.removeChild(el.firstChild);
      }
      newDiv = domify(html);
      return el.appendChild(newDiv);
    } else {
      return el.innerHTML;
    }
  };

  return util;

})();

myutil = new util();


/**
 * tracker class
#
 */

tracker = (function() {
  function tracker() {}

  tracker.prototype.defaults = webanalyser.getResult();

  tracker.prototype.pixel = '/pixel.gif';

  tracker.prototype.siteid = 0;

  tracker.prototype.store = null;

  tracker.prototype.uuid = null;

  tracker.prototype._trackit = function(myData, pixel) {
    var self;
    self = this;
    myData.uuid = self.uuid;
    myData.siteid = self.siteid;
    myData.usid = $sessionid;
    getImage(pixel, query.stringify(myData));
    self.emit('track', myData.ht, myData);
    return self;
  };

  tracker.prototype._track = function(ht, extra) {
    var data, i, k, len, myData, myDef, pixel, self, v;
    self = this;
    if (extra == null) {
      extra = {};
    }
    if (self.siteid > 0) {
      pixel = myutil.trim(this.pixel);
      myDef = self.defaults;
      if ((pixel.indexOf('//') === 0) && (myDef.dl.indexOf('http') !== 0)) {
        pixel = 'http:' + pixel;
      }
      data = ht === 'pageview' ? defaults(extra, myDef) : extra;
      myData = {};
      for (v = i = 0, len = data.length; i < len; v = ++i) {
        k = data[v];
        if (v != null) {
          if (!(typeof v === "string") || (myutil.trim(v).length > 0)) {
            myData[k] = v;
          }
        }
      }
      myData.z = new Date().getTime();
      myData.ht = ht;
      if (!self.uuid) {
        self.uuid = uuid();
      }
      if (self.store != null) {
        self.store.get('trakless-uuid').then(function(id) {
          if (!id) {
            self.store.set('trakless-uuid', self.uuid);
          }
          self.uuid = id || self.uuid;
          return self._trackit(myData, pixel);
        });
      } else {
        self._trackit(myData, pixel);
      }
    }
    return this;
  };


  /**
   * track generic method
  #
   * @param {String} ht - hit types with possible values of 'pageview', 'event', 'transaction', 'item', 'social', 'exception', 'timing', 'app', 'custom'
   * @param {Object} extra - extended data
   * @return {Object}
   */

  tracker.prototype.track = function(ht, extra) {
    var self;
    self = this;
    myutil.ready(function() {
      return self._track(ht || 'custom', extra);
    });
    return this;
  };


  /**
   * track pageview
  #
   * @param {Object} extra - extended data
   * @return {Object}
   */

  tracker.prototype.trackPageView = function(extra) {
    return this.track('pageview', extra);
  };


  /**
   * track event
  #
   * @param {String} category
   * @param {String} action
   * @param {String} label
   * @param {String} value - Values must be non-negative.
   * @return {Object}
   */

  tracker.prototype.trackEvent = function(category, action, label, value) {
    if (value && value < 0) {
      value = null;
    }
    return this.track('event', {
      ec: category || 'event',
      ea: action,
      el: label,
      ev: value
    });
  };


  /**
   * track item
  #
   * @param {String} id - *required* [OD564]
   * @param {Number} name - *required* [Shoe] Specifies the item name.
   * @param {Number} price [3.50] Specifies the price for a single item / unit.
   * @param {Number} quantity [4] Specifies the number of items purchased.
   * @param {String} code [SKU47] Specifies the SKU or item code.
   * @param {String} category [Blue] Specifies the category that the item belongs to.
   * @param {String} currencycode [EUR] When present indicates the local currency for all transaction currency values. Value should be a valid ISO 4217 currency code.
   * @return {Object}
   */

  tracker.prototype.trackItemOrTransaction = function(id, name, price, quantity, code, category, currencycode) {
    return this.track('item', {
      ti: id,
      "in": name,
      ip: price,
      iq: quantity,
      ic: code,
      iv: category,
      cu: currencycode
    });
  };


  /**
   * track transaction
  #
   * @param {String} id - *required* [OD564]
   * @param {String} affiliation [Member] Specifies the affiliation or store name.
   * @param {Number} revenue [15.47] Specifies the total revenue associated with the transaction. This value should include any shipping or tax costs.
   * @param {Number} shipping [3.50] Specifies the total shipping cost of the transaction.
   * @param {Number} tax [1.20] Specifies the total tax of the transaction.
   * @param {Number} price [3.50] Specifies the price for a single item / unit.
   * @param {Number} quantity [4] Specifies the number of items purchased.
   * @param {String} code [SKU47] Specifies the SKU or item code.
   * @param {String} category [Blue] Specifies the category that the item belongs to.
   * @param {String} currencycode [EUR] When present indicates the local currency for all transaction currency values. Value should be a valid ISO 4217 currency code.
   * @return {Object}
   */

  tracker.prototype.trackTransaction = function(id, affiliation, revenue, shipping, tax, name, price, quantity, code, category, currencycode) {
    return this.track('transaction', {
      ti: id,
      ta: affiliation,
      tr: revenue,
      ts: shipping,
      tt: tax,
      "in": name,
      ip: price,
      iq: quantity,
      ic: code,
      iv: category,
      cu: currencycode
    });
  };


  /**
   * track social
  #
   * @param {String} network - *required* [facebook] Specifies the social network, for example Facebook or Google Plus.
   * @param {String} action - *required* [like] Specifies the social interaction action. For example on Google Plus when a user clicks the +1 button, the social action is 'plus'.
   * @param {String} target - *required* [http://foo.com] Specifies the target of a social interaction. This value is typically a URL but can be any text.
   * @return {Object}
   */

  tracker.prototype.trackSocial = function(network, action, target) {
    return this.track('social', {
      sn: network,
      sa: action,
      st: target
    });
  };


  /**
   * track exception
  #
   * @param {String} description - Specifies the description of an exception.
   * @param {String} isFatal - true/false Specifies whether the exception was fatal.
   * @return {Object}
   */

  tracker.prototype.trackException = function(description, isFatal) {
    return this.track('exception', {
      exf: isFatal ? 1 : 0,
      exd: description
    });
  };


  /**
   * track app
  #
   * @param {String} name - *required* [MyApp] Specifies the application name.
   * @param {String} id - *required* [com.company.app] Application identifier.
   * @param {String} version - *required* [1.2] Specifies the application version.
   * @param {String} installerid - *required* com.platform.vending
   * @return {Object}
   */

  tracker.prototype.trackApp = function(name, id, version, installerid) {
    return this.track('app', {
      an: name,
      aid: id,
      av: version,
      aiid: installer
    });
  };


  /**
   * track custom
  #
   * @param {Object} customDataObject - object with any property you want
   * @return {Object}
   */

  tracker.prototype.trackCustom = function(customDataObject) {
    return this.track('custom', customDataObject);
  };

  return tracker;

})();

Emitter(tracker.prototype);


/**
 * tracker factory
#
 */

mytrakless = (function() {
  function mytrakless() {}


  /**
   * set default siteid
  #
   * @param {Number} siteid - the site id
   * @return {Object}
   */

  mytrakless.prototype.setSiteId = function(siteid) {
    $siteid = siteid > 0 ? siteid : $siteid;
  };


  /**
   * set default pixel
  #
   * @param {String} pixel - the default pixel url
   * @return {Object}
   */

  mytrakless.prototype.setPixel = function(pixelUrl) {
    $pixel = pixelUrl || $pixel;
  };


  /**
   * the storage
  #
   * @return {Object}
   */

  mytrakless.prototype.store = xstore;


  /**
   * you can provide different siteid and pixelUrl for in multi-tracker and site scenario
  #
   * @param {Number} siteid - the siteid
   * @param {String} pixelUrl - the pixel url
   * @return {Object}
   */

  mytrakless.prototype.getTracker = function(siteid, pixelUrl) {
    var rst;
    rst = new tracker(siteid, pixelUrl);
    rst.siteid = siteid || $siteid;
    rst.pixel = pixelUrl || $pixel;
    rst.store = xstore;
    return rst;
  };


  /**
   * get the default racker
  #
   */

  mytrakless.prototype.getDefaultTracker = function() {
    if ($defaultTracker == null) {
      $defaultTracker = trakless.getTracker();
    }
    return $defaultTracker;
  };


  /**
   * utility
  #
   */

  mytrakless.prototype.util = myutil;


  /**
   * similar to emit, except it broadcast to parent
  #
   */

  mytrakless.prototype.broadcast = function(en, ed) {
    if (typeof $trakless2 !== "undefined" && $trakless2 !== null) {
      $trakless2.emit(en, ed);
    }
    return this;
  };

  return mytrakless;

})();

trakless = new mytrakless;

Emitter(trakless);

$trakless2 = trakless;

if (win.top !== win) {
  try {
    traklessParent = win.top.trakless;
    $trakless2 = traklessParent;
  } catch (_error) {
    $trakless2 = win.parent.trakless;
  }
}

attrs = {
  site: function(value) {
    return trakless.setSiteId(value);
  },
  pixel: function(value) {
    if (typeof value !== "string") {
      return;
    }
    return trakless.setPixel(value);
  }
};

ref = win.document.getElementsByTagName("script");
for (i = 0, len = ref.length; i < len; i++) {
  script = ref[i];
  if (/trakless/i.test(script.src)) {
    ref1 = ['', 'data-'];
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      prefix = ref1[j];
      for (k in attrs) {
        fn = attrs[k];
        fn(script.getAttribute(prefix + k));
      }
    }
  }
}

win.trakless = trakless;

module.exports = trakless;
